INSERT INTO ORDERS(CODE, CUSTOMER_NAME, STATUS, CREATE_DATE) VALUES (1, 'ciccio customer', 0, TIMESTAMP'2023-08-26 11:08:01.0');

INSERT INTO ORDER_PIZZA(ORDER_CODE, PIZZA_NAME) VALUES (1, 'diavola');