INSERT INTO PIZZA(NAME, COST) VALUES ('margherita', 6);
INSERT INTO PIZZA(NAME, COST) VALUES ('bufalina', 8);
INSERT INTO PIZZA(NAME, COST) VALUES ('quattro formaggi', 8);
INSERT INTO PIZZA(NAME, COST) VALUES ('diavola', 7.5);
INSERT INTO PIZZA(NAME, COST) VALUES ('porcini e speck', 9.5);